# Generated by Django 4.2.7 on 2025-11-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in ETB', max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('transaction_id', models.CharField(blank=True, help_text='Chapa transaction reference', max_length=255, null=True, unique=True)),
                ('chapa_reference', models.CharField(help_text='Unique reference for Chapa payment', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('chapa_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='listings_pa_transac_0240af_idx'), models.Index(fields=['chapa_reference'], name='listings_pa_chapa_r_61c2fc_idx'), models.Index(fields=['status'], name='listings_pa_status_98563c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['host'], name='listings_li_host_id_add4f5_idx'), models.Index(fields=['is_active'], name='listings_li_is_acti_03d721_idx')],
            },
        ),
    ]
